[colors.primary]
background = "#000000"

[font]
size = 16

[font.normal]
# family = "Iosevka Nerd Font"
family = "BerkeleyMono Nerd Font"
# family = "UbuntuMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
