[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
# background = "#0F1419"
background = "#111111"
foreground = "#ebdbb2"

[font]
size = 16

[font.normal]
family = "BerkeleyMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.9
